export const menuItemsData = [
  {
    "id": 1,
    "name": "Bánh Bao",
    "info": "Lớp bánh mềm mỏng, với nhân thịt băm bên trong, trứng cút..",
    "price": 12,
    "img": "/images/banhbao.jpg",
  },
  {
    "id": 2,
    "name": "Bánh Cuốn",
    "info": "Bánh cuốn nóng hổi, vừa ăn vừa thổi, nhân thịt ngọt, mềm.",
    "price": 24,
    "img": "/images/banhcuon.jpg",
  },
  {
    "id": 3,
    "name": "Bánh Khọt",
    "info": "Đế bánh giòn tan, cùng với nhân tôm tươi, hoà quyện cùng nước chấm",
    "price": 24,
    "img": "/images/banhkhot.jpg",
  },
  {
    "id": 4,
    "name": "Bánh Mì",
    "info": "Vỏ bánh mì giòn tan, cùng với nhân thịt nướng, pate, nước sốt.",
    "price": 24,
    "img": "/images/banhmi.jpg",
  },
  {
    "id": 5,
    "name": 'Bánh Xèo',
    "info": 'Bánh xèo nóng hổi, cùng nhân tôm, thịt thơm nức mũi.',
    "price": 24,
    "img": '/images/banhxeo.jpg',
  },
  {
    "id": 6,
    "name": 'Bò xào rau củ',
    "info": 'Bò nhập khẩu từ Mỹ, cùng với rau củ tươi Đà Lạt.',
    "price": 24,
    "img": '/images/bo-xao-rau-cu.jpg',
  },
  {
    "id": 7,
    "name": 'Bún Giò',
    "info": 'Món ăn quen thuộc, với sợi bún dai dai, giò heo tươi mềm.',
    "price": 24,
    "img": '/images/bungio.jpg',
  },
  {
    "id": 8,
    "name": 'Chả cá',
    "info": 'Chả cá Thác Lác, tươi ngon, không chất bảo quản, 100% từ cá.',
    "price": 24,
    "img": '/images/chaca.jpg',
  },
  {
    "id": 9,
    "name": 'Cơm Tấm',
    "info": 'Cơm tấm, sườn, bì, chả trứng, món ăn đặc sản Sài Gòn!',
    "price": 24,
    "img": '/images/comtam.jpg',
  },
  {
    "id": 10,
    "name": 'Hủ Tiếu',
    "info": 'HỦ tiếu Nam Vang, cùng với nước hầm ngon từ thịt ngọt từ xương.',
    "price": 24,
    "img": '/images/hutieu.jpg',
  },
  {
    "id": 11,
    "name": 'Mì Quảng',
    "info": 'Đặc sản Quảng Nam, Đà Nẵng, với tôm thịt, rau sống.',
    "price": 24,
    "img": '/images/miquang.jpg',
  },
  {
    "id": 12,
    "name": 'Nem rán',
    "info": 'Nem rán nóng hổi giòn rụm, ăn mãi chỉ no không ngán.',
    "price": 24,
    "img": '/images/nemran.jpg',
  },
  {
    "id": 13,
    "name": 'Phở Bò',
    "info": 'Phở Bò Huế, thơm ngon đến giọt nước cuối cùng.',
    "price": 24,
    "img": '/images/phobo.jpg',
  },
  {
    "id": 14,
    "name": 'Sườn xào',
    "info": 'Sườn xào chua ngọt, 100% sườn non, sốt chua ngọt đậm vị.',
    "price": 24,
    "img": '/images/suonxao.jpg',
  },
  {
    "id": 15,
    "name": 'Xôi thập cẩm',
    "info": 'Xôi thập cẩm, chấm cùng muối lạc, món ăn tuổi thơ.',
    "price": 24,
    "img": '/images/xoi.jpg',
  },
  {
    "id": 16,
    "name": 'Cơm trộn',
    "info": 'Cơm trộn với trứng, thịt bò, rau củ tươi, sốt ăn kèm đậm vị.',
    "price": 24,
    "img": '/images/comtron.jpg',
  },
  {
    "id": "17",
    "name": "Cơm trắng thịt kho",
    "info": "Không gì bằng một chén cơm trắng nóng hổi, cùng với miếng thịt kho thơm ngất.",
    "price": "24",
    "img": "/images/comtrang.jpg",
  },
];
